---@TODO:
    --a Options Dock where one can toggle especific cube parameters
    --mouse panning and better pivot controls
    --Game Objects placements (like doors, items, enemies, etc)
    --Dynamic cubes should not be included in the exported save.obj
