---@TODO: 
---@Implement:
    --a selection cube that can be moved in 3D space by pressing wasd/arrow keys, this selection cube enable the edit of the overlaping cube.
    --a minimize button in each Label Dock
    --a Options Dock where one can toggle especific cube parameters